version: '3.9'

services:
  chat:
    container_name: chat
    restart: on-failure
    build:
      context: ./chat
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host=0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./chat/.env       
    volumes:
      - ./chat/src:/src/
      - ./chat/models:/models/
    depends_on:
      - redis
    networks:
      - net          

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "6380:8001"
    volumes:
      - redis-data:/data
    environment:
      REDIS_ARGS: "--save 60 1000 --appendonly no"
    networks:
      - net

volumes:
  redis-data:
    driver: local

networks:
  net:
    driver: bridge